version: '3.8'

services:
  db:
    container_name: ecommerce-postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: muros
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: ecommerce
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: