version: '3.8'

services:
  db:
    container_name: ecommerce-mysql
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: muros
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    restart: unless-stopped
#  api:
#    container_name: ecommerce-api
#    image: nicomuros/backend
#    ports:
#      - "8080:8080"
#    networks:
#      - db
#    depends_on:
#      - db
#    restart: unless-stopped
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://ecommerce-mysql:3306/ecommerce
networks:
  db:
    driver: bridge
volumes:
  db: