version: '3.8'

services:
  db:
    container_name: ecommerce-postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: muros
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: ecommerce
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
  api:
    container_name: ecommerce-api
    image: nicomuros/backend
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ecommerce-postgres:5432/ecommerce
networks:
  db:
    driver: bridge
volumes:
  db: