  server:
    port: 8080
    error:
      include-message: always

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/ecommerce
      username: muros
      password: password
    jpa:
      hibernate:
        ddl-auto: create-drop #Que cree los schema y los elimine cuando termina
      properties:
        hibernate:
          #Esta propiedad especifica el dialecto de base de datos que Hibernate
          # utilizará para generar SQL específico de PostgreSQL.
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: false

    main:
      web-application-type: servlet